-- Insert sample data into users table
-- All users have password: 12345678 (BCrypt encoded)
INSERT INTO users (username, password, email, role) VALUES
('admin', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'admin@example.com', 'ADMIN'),
('faculty1', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'faculty1@example.com', 'FACULTY'),
('faculty2', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'faculty2@example.com', 'FACULTY'),
('student1', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'student1@example.com', 'STUDENT'),
('student2', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'student2@example.com', 'STUDENT'),
('student3', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'student3@example.com', 'STUDENT'),
('student4', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'student4@example.com', 'STUDENT'),
('student5', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'student5@example.com', 'STUDENT'),
('student6', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'student6@example.com', 'STUDENT'),
('principal', '$2a$10$rOzJqJ5Y6X3X6X3X6X3X6u', 'principal@example.com', 'PRINCIPAL');

-- Insert sample data into exams table
INSERT INTO exams (subject, durationMinutes, dateTime) VALUES
('Mathematics', 60, '2024-01-15 10:00:00'),
('Physics', 45, '2024-01-16 11:00:00'),
('Chemistry', 50, '2024-01-17 09:30:00'),
('Biology', 55, '2024-01-18 14:00:00'),
('English', 40, '2024-01-19 10:30:00'),
('History', 35, '2024-01-20 13:00:00'),
('Geography', 45, '2024-01-21 15:00:00'),
('Computer Science', 70, '2024-01-22 16:00:00'),
('Economics', 50, '2024-01-23 11:30:00'),
('Business Studies', 45, '2024-01-24 14:30:00');

-- Insert sample data into questions table
INSERT INTO questions (exam_id, text, optionA, optionB, optionC, optionD, correctAnswer) VALUES
(1, 'What is 2 + 2?', '3', '4', '5', '6', 'B'),
(1, 'Solve for x: 3x + 5 = 20', '5', '6', '7', '8', 'A'),
(1, 'What is the square root of 64?', '6', '7', '8', '9', 'C'),
(1, 'Calculate 15% of 200', '20', '25', '30', '35', 'C'),
(1, 'What is the value of π (pi)?', '3.14', '3.15', '3.16', '3.17', 'A'),
(1, 'Solve: 2^4 + 3^2', '10', '11', '12', '13', 'B'),
(1, 'What is 12 × 7?', '82', '83', '84', '85', 'C'),
(1, 'Find the area of a circle with radius 5', '25π', '50π', '75π', '100π', 'A'),
(1, 'What is 144 ÷ 12?', '10', '11', '12', '13', 'C'),
(1, 'Solve: 3(x + 2) = 15', '3', '4', '5', '6', 'A'),

(2, 'What is the SI unit of force?', 'Newton', 'Joule', 'Watt', 'Pascal', 'A'),
(2, 'Who discovered gravity?', 'Einstein', 'Newton', 'Galileo', 'Tesla', 'B'),
(2, 'What is the speed of light?', '299,792 km/s', '300,000 km/s', '250,000 km/s', '350,000 km/s', 'A'),
(2, 'What is kinetic energy?', 'Energy at rest', 'Energy in motion', 'Thermal energy', 'Electrical energy', 'B'),
(2, 'What is voltage measured in?', 'Amperes', 'Volts', 'Ohms', 'Watts', 'B'),
(2, 'What is the formula for force?', 'F = ma', 'F = mv', 'F = m/a', 'F = v/t', 'A'),
(2, 'What is the unit of power?', 'Joule', 'Watt', 'Newton', 'Volt', 'B'),
(2, 'What is the law of conservation of energy?', 'Energy can be created', 'Energy can be destroyed', 'Energy cannot be created or destroyed', 'Energy is constant', 'C'),
(2, 'What is acceleration due to gravity?', '9.8 m/s²', '10 m/s²', '8.9 m/s²', '11 m/s²', 'A'),
(2, 'What is the atomic number?', 'Number of protons', 'Number of neutrons', 'Number of electrons', 'Total particles', 'A'),

(3, 'What is H2O?', 'Water', 'Hydrogen', 'Oxygen', 'Hydrogen peroxide', 'A'),
(3, 'What is the pH of pure water?', '5', '6', '7', '8', 'C'),
(3, 'What is the atomic symbol for gold?', 'Go', 'Gd', 'Au', 'Ag', 'C'),
(3, 'What is the most abundant gas in atmosphere?', 'Oxygen', 'Nitrogen', 'Carbon dioxide', 'Argon', 'B'),
(3, 'What is the chemical formula for table salt?', 'NaCl', 'KCl', 'CaCl2', 'MgCl2', 'A'),
(3, 'What is the pH of lemon juice?', '2-3', '4-5', '6-7', '8-9', 'A'),
(3, 'What is the atomic number of carbon?', '6', '7', '8', '9', 'A'),
(3, 'What is oxidation?', 'Loss of electrons', 'Gain of electrons', 'Loss of protons', 'Gain of protons', 'A'),
(3, 'What is the formula for sulfuric acid?', 'H2SO4', 'HCl', 'HNO3', 'H3PO4', 'A'),
(3, 'What is the state of mercury at room temperature?', 'Solid', 'Liquid', 'Gas', 'Plasma', 'B'),
(3, 'What is the symbol for iron?', 'Ir', 'Fe', 'In', 'I', 'B'),
(3, 'What is the main component of natural gas?', 'Methane', 'Ethane', 'Propane', 'Butane', 'A'),

(4, 'What is the powerhouse of the cell?', 'Nucleus', 'Mitochondria', 'Ribosome', 'Golgi apparatus', 'B'),
(4, 'How many chromosomes do humans have?', '23', '46', '48', '50', 'B'),
(4, 'What is photosynthesis?', 'Process of making food in plants', 'Process of respiration', 'Process of digestion', 'Process of excretion', 'A'),
(4, 'What is the largest organ in human body?', 'Liver', 'Heart', 'Skin', 'Lungs', 'C'),
(4, 'What is DNA?', 'Deoxyribonucleic Acid', 'Nucleic Acid', 'Protein', 'Enzyme', 'A'),
(4, 'What is the function of red blood cells?', 'Carry oxygen', 'Fight infection', 'Clot blood', 'Digest food', 'A'),
(4, 'What is the smallest unit of life?', 'Cell', 'Atom', 'Molecule', 'Organ', 'A'),
(4, 'What is the study of plants called?', 'Zoology', 'Botany', 'Biology', 'Ecology', 'B'),
(4, 'What is the main function of kidneys?', 'Pump blood', 'Filter blood', 'Digest food', 'Produce hormones', 'B'),
(4, 'What is the process of cell division called?', 'Mitosis', 'Meiosis', 'Both', 'None', 'C'),

(5, 'Who wrote Romeo and Juliet?', 'Charles Dickens', 'William Shakespeare', 'Jane Austen', 'Mark Twain', 'B'),
(5, 'What is a synonym for "happy"?', 'Sad', 'Joyful', 'Angry', 'Tired', 'B'),
(5, 'What is the past tense of "go"?', 'Goed', 'Went', 'Gone', 'Going', 'B'),
(5, 'How many syllables in "beautiful"?', '2', '3', '4', '5', 'B'),
(5, 'What is a metaphor?', 'Comparison using like or as', 'Direct comparison', 'Exaggeration', 'Contradiction', 'B'),
(5, 'Who wrote "Pride and Prejudice"?', 'Emily Bronte', 'Jane Austen', 'Charlotte Bronte', 'Charles Dickens', 'B'),
(5, 'What is the plural of "child"?', 'Childs', 'Children', 'Childes', 'Childen', 'B'),
(5, 'What is the main verb in "She is running"?', 'She', 'is', 'running', 'is running', 'C'),
(5, 'What is a proper noun?', 'General name', 'Specific name', 'Action word', 'Describing word', 'B'),
(5, 'What is the opposite of "ancient"?', 'Old', 'Modern', 'Historic', 'Traditional', 'B'),

(6, 'When did World War II end?', '1943', '1944', '1945', '1946', 'C'),
(6, 'Who was the first President of the USA?', 'Thomas Jefferson', 'George Washington', 'Abraham Lincoln', 'John Adams', 'B'),
(6, 'What ancient civilization built the pyramids?', 'Romans', 'Greeks', 'Egyptians', 'Mayans', 'C'),
(6, 'When did India gain independence?', '1945', '1946', '1947', '1948', 'C'),
(6, 'Who discovered America?', 'Christopher Columbus', 'Vasco da Gama', 'Marco Polo', 'James Cook', 'A'),
(6, 'What was the capital of ancient Rome?', 'Athens', 'Rome', 'Constantinople', 'Alexandria', 'B'),
(6, 'When was the French Revolution?', '1789', '1799', '1809', '1819', 'A'),
(6, 'Who was the first woman Prime Minister of India?', 'Sonia Gandhi', 'Indira Gandhi', 'Margaret Thatcher', 'Angela Merkel', 'B'),
(6, 'What was the main cause of World War I?', 'Economic crisis', 'Assassination of Archduke', 'Religious conflict', 'Territorial dispute', 'B'),
(6, 'When did the Cold War end?', '1985', '1989', '1991', '1995', 'C'),

(7, 'What is the capital of France?', 'London', 'Berlin', 'Paris', 'Madrid', 'C'),
(7, 'Which is the largest ocean?', 'Atlantic', 'Indian', 'Arctic', 'Pacific', 'D'),
(7, 'What is the longest river in the world?', 'Amazon', 'Nile', 'Mississippi', 'Yangtze', 'B'),
(7, 'Which continent is the largest?', 'Africa', 'Asia', 'North America', 'Europe', 'B'),
(7, 'What is the capital of Japan?', 'Seoul', 'Beijing', 'Tokyo', 'Bangkok', 'C'),
(7, 'Which desert is the largest?', 'Sahara', 'Gobi', 'Kalahari', 'Arabian', 'A'),
(7, 'What is the highest mountain?', 'K2', 'Kangchenjunga', 'Mount Everest', 'Lhotse', 'C'),
(7, 'Which country has the most population?', 'India', 'USA', 'China', 'Russia', 'C'),
(7, 'What is the capital of Australia?', 'Sydney', 'Melbourne', 'Canberra', 'Perth', 'C'),
(7, 'Which is the smallest continent?', 'Europe', 'Australia', 'Antarctica', 'South America', 'B'),

(8, 'What does CPU stand for?', 'Central Processing Unit', 'Computer Personal Unit', 'Central Processor Unit', 'Central Program Unit', 'A'),
(8, 'What is the binary equivalent of decimal 10?', '1010', '1001', '1100', '1011', 'A'),
(8, 'What is RAM?', 'Read Access Memory', 'Random Access Memory', 'Rapid Access Memory', 'Readily Available Memory', 'B'),
(8, 'Who is known as the father of computers?', 'Bill Gates', 'Steve Jobs', 'Charles Babbage', 'Alan Turing', 'C'),
(8, 'What is an algorithm?', 'Hardware device', 'Step-by-step procedure', 'Programming language', 'Computer virus', 'B'),
(8, 'What does HTML stand for?', 'Hyper Text Markup Language', 'High Tech Modern Language', 'Hyper Transfer Markup Language', 'High Text Modern Language', 'A'),
(8, 'What is the extension of Python files?', '.java', '.py', '.cpp', '.js', 'B'),
(8, 'What is cloud computing?', 'Weather forecasting', 'Internet-based computing', 'Gaming platform', 'Social media', 'B'),
(8, 'What is a firewall?', 'Security system', 'Cooling system', 'Networking device', 'Storage device', 'A'),
(8, 'What is the main function of an operating system?', 'Run applications', 'Manage hardware resources', 'Create documents', 'Browse internet', 'B'),

(9, 'What is economics?', 'Study of money', 'Study of production and consumption', 'Study of politics', 'Study of society', 'B'),
(9, 'What is GDP?', 'Gross Domestic Product', 'General Domestic Price', 'Gross Development Product', 'General Development Price', 'A'),
(9, 'What is inflation?', 'Increase in prices', 'Decrease in prices', 'Stable prices', 'No prices', 'A'),
(9, 'What is a monopoly?', 'Many sellers', 'One seller', 'No sellers', 'Government seller', 'B'),
(9, 'What is supply and demand?', 'Economic theory', 'Political theory', 'Social theory', 'Scientific theory', 'A'),
(9, 'What is a recession?', 'Economic growth', 'Economic decline', 'Stable economy', 'No economy', 'B'),
(9, 'What is capitalism?', 'Government control', 'Private ownership', 'No ownership', 'Mixed ownership', 'B'),
(9, 'What is a stock market?', 'Where stocks are traded', 'Where goods are sold', 'Where money is printed', 'Where taxes are paid', 'A'),
(9, 'What is interest rate?', 'Price of money', 'Price of goods', 'Price of services', 'Price of time', 'A'),
(9, 'What is unemployment rate?', 'Percentage of employed', 'Percentage of unemployed', 'Percentage of population', 'Percentage of workers', 'B'),

(10, 'What is entrepreneurship?', 'Starting a business', 'Working for government', 'Studying business', 'Managing money', 'A'),
(10, 'What is marketing?', 'Selling products', 'Promoting products', 'Making products', 'Pricing products', 'B'),
(10, 'What is SWOT analysis?', 'Strengths, Weaknesses, Opportunities, Threats', 'Sales, Wealth, Operations, Technology', 'Strategy, Work, Organization, Time', 'System, Workforce, Output, Training', 'A'),
(10, 'What is a business plan?', 'Legal document', 'Financial document', 'Strategic document', 'All of the above', 'D'),
(10, 'What is ROI?', 'Return on Investment', 'Rate of Interest', 'Return on Income', 'Rate of Investment', 'A'),
(10, 'What is CRM?', 'Customer Relationship Management', 'Company Resource Management', 'Corporate Revenue Management', 'Customer Revenue Management', 'A'),
(10, 'What is a startup?', 'New business', 'Small business', 'Large business', 'Government business', 'A'),
(10, 'What is venture capital?', 'Government funding', 'Private investment', 'Bank loan', 'Personal savings', 'B'),
(10, 'What is e-commerce?', 'Electronic commerce', 'Economic commerce', 'Enterprise commerce', 'Online commerce', 'A'),
(10, 'What is a balance sheet?', 'Financial statement', 'Business plan', 'Marketing strategy', 'Legal document', 'A');

-- Insert sample data into results table
-- Using student IDs 4-9 (students 1-6) since they exist in the users table
INSERT INTO results (exam_id, student_id, score, status) VALUES
(1, 4, 85, 'PASS'),
(1, 5, 92, 'PASS'),
(1, 6, 78, 'PASS'),
(1, 7, 65, 'PASS'),
(1, 8, 45, 'FAIL'),
(1, 9, 88, 'PASS'),
(2, 4, 88, 'PASS'),
(2, 5, 95, 'PASS'),
(2, 6, 72, 'PASS'),
(2, 7, 58, 'PASS'),
(2, 8, 82, 'PASS'),
(2, 9, 91, 'PASS'),
(3, 4, 91, 'PASS'),
(3, 5, 84, 'PASS'),
(3, 6, 67, 'PASS'),
(3, 7, 73, 'PASS'),
(3, 8, 49, 'FAIL'),
(3, 9, 76, 'PASS'),
(4, 4, 96, 'PASS'),
(4, 5, 89, 'PASS'),
(4, 6, 75, 'PASS'),
(4, 7, 62, 'PASS'),
(4, 8, 87, 'PASS'),
(4, 9, 93, 'PASS'),
(5, 4, 83, 'PASS'),
(5, 5, 90, 'PASS'),
(5, 6, 71, 'PASS'),
(5, 7, 66, 'PASS'),
(5, 8, 54, 'PASS'),
(5, 9, 79, 'PASS'),
(6, 4, 94, 'PASS'),
(6, 5, 86, 'PASS'),
(6, 6, 79, 'PASS'),
(6, 7, 63, 'PASS'),
(6, 8, 47, 'FAIL'),
(6, 9, 82, 'PASS'),
(7, 4, 97, 'PASS'),
(7, 5, 88, 'PASS'),
(7, 6, 74, 'PASS'),
(7, 7, 69, 'PASS'),
(7, 8, 82, 'PASS'),
(7, 9, 95, 'PASS'),
(8, 4, 91, 'PASS'),
(8, 5, 93, 'PASS'),
(8, 6, 76, 'PASS'),
(8, 7, 61, 'PASS'),
(8, 8, 85, 'PASS'),
(8, 9, 88, 'PASS'),
(9, 4, 89, 'PASS'),
(9, 5, 95, 'PASS'),
(9, 6, 72, 'PASS'),
(9, 7, 68, 'PASS'),
(9, 8, 51, 'PASS'),
(9, 9, 84, 'PASS'),
(10, 4, 92, 'PASS'),
(10, 5, 87, 'PASS'),
(10, 6, 78, 'PASS'),
(10, 7, 64, 'PASS'),
(10, 8, 43, 'FAIL'),
(10, 9, 89, 'PASS');
